/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { DataStruct } from "../DataStruct";

export class DataStruct__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DataStruct> {
    return super.deploy(overrides || {}) as Promise<DataStruct>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DataStruct {
    return super.attach(address) as DataStruct;
  }
  connect(signer: Signer): DataStruct__factory {
    return super.connect(signer) as DataStruct__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DataStruct {
    return new Contract(address, _abi, signerOrProvider) as DataStruct;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x26781d8b",
        type: "bytes32",
      },
    ],
    name: "c_0x26781d8b",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60a3610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c80632e7a666f146038575b600080fd5b604e6004803603810190604a91906053565b6050565b005b50565b6000602082840312156063578081fd5b813590509291505056fea26469706673582212202d1347f6920294216348b4115c475ca80efeaeb9d9443234d042227f46600e4264736f6c63430008030033";
