/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { MoneyPoolStorage } from "../MoneyPoolStorage";

export class MoneyPoolStorage__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MoneyPoolStorage> {
    return super.deploy(overrides || {}) as Promise<MoneyPoolStorage>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MoneyPoolStorage {
    return super.attach(address) as MoneyPoolStorage;
  }
  connect(signer: Signer): MoneyPoolStorage__factory {
    return super.connect(signer) as MoneyPoolStorage__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MoneyPoolStorage {
    return new Contract(address, _abi, signerOrProvider) as MoneyPoolStorage;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x4be3a3be",
        type: "bytes32",
      },
    ],
    name: "c_0x4be3a3be",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b5060988061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063df45787a14602d575b600080fd5b60436004803603810190603f91906048565b6045565b005b50565b6000602082840312156058578081fd5b813590509291505056fea2646970667358221220e0a39bb4194d84943fd8609885f559b4a42df224aa09c813744080c519aa2b5664736f6c63430008030033";
