/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { Role } from "../Role";

export class Role__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Role> {
    return super.deploy(overrides || {}) as Promise<Role>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Role {
    return super.attach(address) as Role;
  }
  connect(signer: Signer): Role__factory {
    return super.connect(signer) as Role__factory;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Role {
    return new Contract(address, _abi, signerOrProvider) as Role;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "c__0x3c18f559",
        type: "bytes32",
      },
    ],
    name: "c_0x3c18f559",
    outputs: [],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x60a3610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c806308bc4bc1146038575b600080fd5b604e6004803603810190604a91906053565b6050565b005b50565b6000602082840312156063578081fd5b813590509291505056fea2646970667358221220564a8ff80b8e89cad600dd78b934ceb1353aebe00c8686d147aa2d6b2a54242264736f6c63430008030033";
