/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  StakingPoolLogic,
  StakingPoolLogicInterface,
} from "../StakingPoolLogic";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "newRewardIndex",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "totalPrincipal",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint8",
        name: "currentRound",
        type: "uint8",
      },
    ],
    name: "UpdateStakingPool",
    type: "event",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212209a7a13499f977d41e27c40ba20241d54eb43511cb7a5a731b7b37085a5446b1664736f6c63430008040033";

export class StakingPoolLogic__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<StakingPoolLogic> {
    return super.deploy(overrides || {}) as Promise<StakingPoolLogic>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): StakingPoolLogic {
    return super.attach(address) as StakingPoolLogic;
  }
  connect(signer: Signer): StakingPoolLogic__factory {
    return super.connect(signer) as StakingPoolLogic__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StakingPoolLogicInterface {
    return new utils.Interface(_abi) as StakingPoolLogicInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StakingPoolLogic {
    return new Contract(address, _abi, signerOrProvider) as StakingPoolLogic;
  }
}
