/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { TokenizerErrors } from "../TokenizerErrors";

export class TokenizerErrors__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<TokenizerErrors> {
    return super.deploy(overrides || {}) as Promise<TokenizerErrors>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TokenizerErrors {
    return super.attach(address) as TokenizerErrors;
  }
  connect(signer: Signer): TokenizerErrors__factory {
    return super.connect(signer) as TokenizerErrors__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenizerErrors {
    return new Contract(address, _abi, signerOrProvider) as TokenizerErrors;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "AssetBondAlreadySettled",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "AssetBondIDAlreadyExists",
    type: "error",
  },
  {
    inputs: [],
    name: "LoanDurationInvalid",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "MintedAssetBondReceiverNotAllowed",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyCollateralServiceProvider",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyCouncil",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyDesignatedSignerAllowed",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyMoneyPool",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "OnlyOwnerHasAuthrotyToSettle",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlySettledTokenSignAllowed",
    type: "error",
  },
  {
    inputs: [],
    name: "SettledLoanStartTimestampInvalid",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "signer",
        type: "address",
      },
    ],
    name: "SignerIsNotCouncil",
    type: "error",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212208264b5475e591fe69fd1d5bf1b0b0d536abbb469b10805b747c47d765458f58664736f6c63430008040033";
