/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { TokenErrors } from "../TokenErrors";

export class TokenErrors__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<TokenErrors> {
    return super.deploy(overrides || {}) as Promise<TokenErrors>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): TokenErrors {
    return super.attach(address) as TokenErrors;
  }
  connect(signer: Signer): TokenErrors__factory {
    return super.connect(signer) as TokenErrors__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): TokenErrors {
    return new Contract(address, _abi, signerOrProvider) as TokenErrors;
  }
}

const _abi = [
  {
    inputs: [],
    name: "DTokenAllowanceNotAllowed",
    type: "error",
  },
  {
    inputs: [],
    name: "DTokenApproveNotAllowed",
    type: "error",
  },
  {
    inputs: [],
    name: "DTokenTransferFromNotAllowed",
    type: "error",
  },
  {
    inputs: [],
    name: "DTokenTransferNotAllowed",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "implicitBalance",
        type: "uint256",
      },
    ],
    name: "LTokenInvalidBurnAmount",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "implicitBalance",
        type: "uint256",
      },
    ],
    name: "LTokenInvalidMintAmount",
    type: "error",
  },
  {
    inputs: [],
    name: "OnlyMoneyPool",
    type: "error",
  },
];

const _bytecode =
  "0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220eceff66c4be068f4238bfb9b1598c0a0aef44d7f4cb4a7052c2bdd9e727b0eb964736f6c63430008040033";
