/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export type AssetBondDataStruct = {
  state: BigNumberish;
  borrower: string;
  signer: string;
  collateralServiceProvider: string;
  principal: BigNumberish;
  debtCeiling: BigNumberish;
  couponRate: BigNumberish;
  interestRate: BigNumberish;
  delinquencyRate: BigNumberish;
  loanStartTimestamp: BigNumberish;
  collateralizeTimestamp: BigNumberish;
  maturityTimestamp: BigNumberish;
  liquidationTimestamp: BigNumberish;
  ipfsHash: string;
  signerOpinionHash: string;
};

export type AssetBondDataStructOutput = [
  number,
  string,
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  string,
  string
] & {
  state: number;
  borrower: string;
  signer: string;
  collateralServiceProvider: string;
  principal: BigNumber;
  debtCeiling: BigNumber;
  couponRate: BigNumber;
  interestRate: BigNumber;
  delinquencyRate: BigNumber;
  loanStartTimestamp: BigNumber;
  collateralizeTimestamp: BigNumber;
  maturityTimestamp: BigNumber;
  liquidationTimestamp: BigNumber;
  ipfsHash: string;
  signerOpinionHash: string;
};

export type AssetBondIdDataStruct = {
  nonce: BigNumberish;
  countryCode: BigNumberish;
  collateralServiceProviderIdentificationNumber: BigNumberish;
  collateralLatitude: BigNumberish;
  collateralLatitudeSign: BigNumberish;
  collateralLongitude: BigNumberish;
  collateralLongitudeSign: BigNumberish;
  collateralDetail: BigNumberish;
  collateralCategory: BigNumberish;
  productNumber: BigNumberish;
};

export type AssetBondIdDataStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  nonce: BigNumber;
  countryCode: BigNumber;
  collateralServiceProviderIdentificationNumber: BigNumber;
  collateralLatitude: BigNumber;
  collateralLatitudeSign: BigNumber;
  collateralLongitude: BigNumber;
  collateralLongitudeSign: BigNumber;
  collateralDetail: BigNumber;
  collateralCategory: BigNumber;
  productNumber: BigNumber;
};

export interface AssetBondInterface extends utils.Interface {
  functions: {
    "getAssetBondDebtData((uint8,address,address,address,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,uint256,string,string))": FunctionFragment;
    "parseAssetBondId(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getAssetBondDebtData",
    values: [AssetBondDataStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "parseAssetBondId",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "getAssetBondDebtData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "parseAssetBondId",
    data: BytesLike
  ): Result;

  events: {};
}

export interface AssetBond extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AssetBondInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAssetBondDebtData(
      assetBondData: AssetBondDataStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    parseAssetBondId(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[AssetBondIdDataStructOutput]>;
  };

  getAssetBondDebtData(
    assetBondData: AssetBondDataStruct,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  parseAssetBondId(
    tokenId: BigNumberish,
    overrides?: CallOverrides
  ): Promise<AssetBondIdDataStructOutput>;

  callStatic: {
    getAssetBondDebtData(
      assetBondData: AssetBondDataStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    parseAssetBondId(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<AssetBondIdDataStructOutput>;
  };

  filters: {};

  estimateGas: {
    getAssetBondDebtData(
      assetBondData: AssetBondDataStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    parseAssetBondId(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getAssetBondDebtData(
      assetBondData: AssetBondDataStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    parseAssetBondId(
      tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
