/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IInterestRateModelInterface extends utils.Interface {
  functions: {
    "calculateRates(uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "calculateRates",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "calculateRates",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IInterestRateModel extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IInterestRateModelInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    calculateRates(
      lTokenAssetBalance: BigNumberish,
      totalDTokenBalance: BigNumberish,
      depositAmount: BigNumberish,
      borrowAmount: BigNumberish,
      moneyPoolFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  calculateRates(
    lTokenAssetBalance: BigNumberish,
    totalDTokenBalance: BigNumberish,
    depositAmount: BigNumberish,
    borrowAmount: BigNumberish,
    moneyPoolFactor: BigNumberish,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber]>;

  callStatic: {
    calculateRates(
      lTokenAssetBalance: BigNumberish,
      totalDTokenBalance: BigNumberish,
      depositAmount: BigNumberish,
      borrowAmount: BigNumberish,
      moneyPoolFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    calculateRates(
      lTokenAssetBalance: BigNumberish,
      totalDTokenBalance: BigNumberish,
      depositAmount: BigNumberish,
      borrowAmount: BigNumberish,
      moneyPoolFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    calculateRates(
      lTokenAssetBalance: BigNumberish,
      totalDTokenBalance: BigNumberish,
      depositAmount: BigNumberish,
      borrowAmount: BigNumberish,
      moneyPoolFactor: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
