/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, Signer, utils } from "ethers";
import { EventFragment } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface RateInterface extends utils.Interface {
  functions: {};

  events: {
    "RatesUpdated(address,uint256,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "RatesUpdated"): EventFragment;
}

export type RatesUpdatedEvent = TypedEvent<
  [string, BigNumber, BigNumber, BigNumber, BigNumber, BigNumber],
  {
    underlyingAssetAddress: string;
    lTokenIndex: BigNumber;
    borrowAPY: BigNumber;
    depositAPY: BigNumber;
    totalBorrow: BigNumber;
    totalDeposit: BigNumber;
  }
>;

export type RatesUpdatedEventFilter = TypedEventFilter<RatesUpdatedEvent>;

export interface Rate extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RateInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "RatesUpdated(address,uint256,uint256,uint256,uint256,uint256)"(
      underlyingAssetAddress?: string | null,
      lTokenIndex?: null,
      borrowAPY?: null,
      depositAPY?: null,
      totalBorrow?: null,
      totalDeposit?: null
    ): RatesUpdatedEventFilter;
    RatesUpdated(
      underlyingAssetAddress?: string | null,
      lTokenIndex?: null,
      borrowAPY?: null,
      depositAPY?: null,
      totalBorrow?: null,
      totalDeposit?: null
    ): RatesUpdatedEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
